name: Release TF

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: googleapis/release-please-action@v4
    with:
      branch: main
      runner: ubuntu-latest
      config-file: release-please-config.json
      manifest-file: .release-please-manifest.json
    secrets:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}